// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/logs/v1/logs.proto

package com.opentelemetry.proto.logs.v1;

public final class LogsProto {
  private LogsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_LogsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_ScopeLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_ScopeLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_logs_v1_LogRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&opentelemetry/proto/logs/v1/logs.proto" +
      "\022\033opentelemetry.proto.logs.v1\032*opentelem" +
      "etry/proto/common/v1/common.proto\032.opent" +
      "elemetry/proto/resource/v1/resource.prot" +
      "o\"Z\n\010LogsData\022N\n\rresource_logs\030\001 \003(\0132).o" +
      "pentelemetry.proto.logs.v1.ResourceLogsR" +
      "\014resourceLogs\"\273\002\n\014ResourceLogs\022E\n\010resour" +
      "ce\030\001 \001(\0132).opentelemetry.proto.resource." +
      "v1.ResourceR\010resource\022E\n\nscope_logs\030\002 \003(" +
      "\0132&.opentelemetry.proto.logs.v1.ScopeLog" +
      "sR\tscopeLogs\022~\n\034instrumentation_library_" +
      "logs\030\350\007 \003(\01327.opentelemetry.proto.logs.v" +
      "1.InstrumentationLibraryLogsB\002\030\001R\032instru" +
      "mentationLibraryLogs\022\035\n\nschema_url\030\003 \001(\t" +
      "R\tschemaUrl\"\276\001\n\tScopeLogs\022I\n\005scope\030\001 \001(\013" +
      "23.opentelemetry.proto.common.v1.Instrum" +
      "entationScopeR\005scope\022G\n\013log_records\030\002 \003(" +
      "\0132&.opentelemetry.proto.logs.v1.LogRecor" +
      "dR\nlogRecords\022\035\n\nschema_url\030\003 \001(\tR\tschem" +
      "aUrl\"\370\001\n\032InstrumentationLibraryLogs\022n\n\027i" +
      "nstrumentation_library\030\001 \001(\01325.opentelem" +
      "etry.proto.common.v1.InstrumentationLibr" +
      "aryR\026instrumentationLibrary\022G\n\013log_recor" +
      "ds\030\002 \003(\0132&.opentelemetry.proto.logs.v1.L" +
      "ogRecordR\nlogRecords\022\035\n\nschema_url\030\003 \001(\t" +
      "R\tschemaUrl:\002\030\001\"\363\003\n\tLogRecord\022$\n\016time_un" +
      "ix_nano\030\001 \001(\006R\014timeUnixNano\0225\n\027observed_" +
      "time_unix_nano\030\013 \001(\006R\024observedTimeUnixNa" +
      "no\022T\n\017severity_number\030\002 \001(\0162+.openteleme" +
      "try.proto.logs.v1.SeverityNumberR\016severi" +
      "tyNumber\022#\n\rseverity_text\030\003 \001(\tR\014severit" +
      "yText\022;\n\004body\030\005 \001(\0132\'.opentelemetry.prot" +
      "o.common.v1.AnyValueR\004body\022G\n\nattributes" +
      "\030\006 \003(\0132\'.opentelemetry.proto.common.v1.K" +
      "eyValueR\nattributes\0228\n\030dropped_attribute" +
      "s_count\030\007 \001(\rR\026droppedAttributesCount\022\024\n" +
      "\005flags\030\010 \001(\007R\005flags\022\031\n\010trace_id\030\t \001(\014R\007t" +
      "raceId\022\027\n\007span_id\030\n \001(\014R\006spanIdJ\004\010\004\020\005*\303\005" +
      "\n\016SeverityNumber\022\037\n\033SEVERITY_NUMBER_UNSP" +
      "ECIFIED\020\000\022\031\n\025SEVERITY_NUMBER_TRACE\020\001\022\032\n\026" +
      "SEVERITY_NUMBER_TRACE2\020\002\022\032\n\026SEVERITY_NUM" +
      "BER_TRACE3\020\003\022\032\n\026SEVERITY_NUMBER_TRACE4\020\004" +
      "\022\031\n\025SEVERITY_NUMBER_DEBUG\020\005\022\032\n\026SEVERITY_" +
      "NUMBER_DEBUG2\020\006\022\032\n\026SEVERITY_NUMBER_DEBUG" +
      "3\020\007\022\032\n\026SEVERITY_NUMBER_DEBUG4\020\010\022\030\n\024SEVER" +
      "ITY_NUMBER_INFO\020\t\022\031\n\025SEVERITY_NUMBER_INF" +
      "O2\020\n\022\031\n\025SEVERITY_NUMBER_INFO3\020\013\022\031\n\025SEVER" +
      "ITY_NUMBER_INFO4\020\014\022\030\n\024SEVERITY_NUMBER_WA" +
      "RN\020\r\022\031\n\025SEVERITY_NUMBER_WARN2\020\016\022\031\n\025SEVER" +
      "ITY_NUMBER_WARN3\020\017\022\031\n\025SEVERITY_NUMBER_WA" +
      "RN4\020\020\022\031\n\025SEVERITY_NUMBER_ERROR\020\021\022\032\n\026SEVE" +
      "RITY_NUMBER_ERROR2\020\022\022\032\n\026SEVERITY_NUMBER_" +
      "ERROR3\020\023\022\032\n\026SEVERITY_NUMBER_ERROR4\020\024\022\031\n\025" +
      "SEVERITY_NUMBER_FATAL\020\025\022\032\n\026SEVERITY_NUMB" +
      "ER_FATAL2\020\026\022\032\n\026SEVERITY_NUMBER_FATAL3\020\027\022" +
      "\032\n\026SEVERITY_NUMBER_FATAL4\020\030*X\n\016LogRecord" +
      "Flags\022\037\n\033LOG_RECORD_FLAG_UNSPECIFIED\020\000\022%" +
      "\n LOG_RECORD_FLAG_TRACE_FLAGS_MASK\020\377\001B\343\001" +
      "\n\037com.opentelemetry.proto.logs.v1B\tLogsP" +
      "rotoP\001Z&go.opentelemetry.io/proto/otlp/l" +
      "ogs/v1\242\002\003OPL\252\002\033Opentelemetry.Proto.Logs." +
      "V1\312\002\033Opentelemetry\\Proto\\Logs\\V1\342\002\'Opent" +
      "elemetry\\Proto\\Logs\\V1\\GPBMetadata\352\002\036Ope" +
      "ntelemetry::Proto::Logs::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          com.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_logs_v1_LogsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_LogsData_descriptor,
        new java.lang.String[] { "ResourceLogs", });
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor,
        new java.lang.String[] { "Resource", "ScopeLogs", "InstrumentationLibraryLogs", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_ScopeLogs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_logs_v1_ScopeLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_ScopeLogs_descriptor,
        new java.lang.String[] { "Scope", "LogRecords", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_InstrumentationLibraryLogs_descriptor,
        new java.lang.String[] { "InstrumentationLibrary", "LogRecords", "SchemaUrl", });
    internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_logs_v1_LogRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_logs_v1_LogRecord_descriptor,
        new java.lang.String[] { "TimeUnixNano", "ObservedTimeUnixNano", "SeverityNumber", "SeverityText", "Body", "Attributes", "DroppedAttributesCount", "Flags", "TraceId", "SpanId", });
    com.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    com.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
