// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/logs/v1/logs.proto

package com.opentelemetry.proto.logs.v1;

/**
 * <pre>
 * A collection of ScopeLogs from a Resource.
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.logs.v1.ResourceLogs}
 */
public final class ResourceLogs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.logs.v1.ResourceLogs)
    ResourceLogsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceLogs.newBuilder() to construct.
  private ResourceLogs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceLogs() {
    scopeLogs_ = java.util.Collections.emptyList();
    instrumentationLibraryLogs_ = java.util.Collections.emptyList();
    schemaUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceLogs();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceLogs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.opentelemetry.proto.resource.v1.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(com.opentelemetry.proto.resource.v1.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              scopeLogs_ = new java.util.ArrayList<com.opentelemetry.proto.logs.v1.ScopeLogs>();
              mutable_bitField0_ |= 0x00000001;
            }
            scopeLogs_.add(
                input.readMessage(com.opentelemetry.proto.logs.v1.ScopeLogs.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            schemaUrl_ = s;
            break;
          }
          case 8002: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              instrumentationLibraryLogs_ = new java.util.ArrayList<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs>();
              mutable_bitField0_ |= 0x00000002;
            }
            instrumentationLibraryLogs_.add(
                input.readMessage(com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        scopeLogs_ = java.util.Collections.unmodifiableList(scopeLogs_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        instrumentationLibraryLogs_ = java.util.Collections.unmodifiableList(instrumentationLibraryLogs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.opentelemetry.proto.logs.v1.LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.opentelemetry.proto.logs.v1.LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.opentelemetry.proto.logs.v1.ResourceLogs.class, com.opentelemetry.proto.logs.v1.ResourceLogs.Builder.class);
  }

  public static final int RESOURCE_FIELD_NUMBER = 1;
  private com.opentelemetry.proto.resource.v1.Resource resource_;
  /**
   * <pre>
   * The resource for the logs in this message.
   * If this field is not set then resource info is unknown.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <pre>
   * The resource for the logs in this message.
   * If this field is not set then resource info is unknown.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
   * @return The resource.
   */
  @java.lang.Override
  public com.opentelemetry.proto.resource.v1.Resource getResource() {
    return resource_ == null ? com.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <pre>
   * The resource for the logs in this message.
   * If this field is not set then resource info is unknown.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
   */
  @java.lang.Override
  public com.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int SCOPE_LOGS_FIELD_NUMBER = 2;
  private java.util.List<com.opentelemetry.proto.logs.v1.ScopeLogs> scopeLogs_;
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.opentelemetry.proto.logs.v1.ScopeLogs> getScopeLogsList() {
    return scopeLogs_;
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder> 
      getScopeLogsOrBuilderList() {
    return scopeLogs_;
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
   */
  @java.lang.Override
  public int getScopeLogsCount() {
    return scopeLogs_.size();
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
   */
  @java.lang.Override
  public com.opentelemetry.proto.logs.v1.ScopeLogs getScopeLogs(int index) {
    return scopeLogs_.get(index);
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
   */
  @java.lang.Override
  public com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder getScopeLogsOrBuilder(
      int index) {
    return scopeLogs_.get(index);
  }

  public static final int INSTRUMENTATION_LIBRARY_LOGS_FIELD_NUMBER = 1000;
  private java.util.List<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs> instrumentationLibraryLogs_;
  /**
   * <pre>
   * A list of InstrumentationLibraryLogs that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
   * scope_logs SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
   * and scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_logs field MAY also set
   * scope_logs to carry the same logs, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_logs and
   * SHOULD NOT set instrumentation_library_logs.
   * JSON receivers SHOULD check if instrumentation_library_logs is set and
   * scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs> getInstrumentationLibraryLogsList() {
    return instrumentationLibraryLogs_;
  }
  /**
   * <pre>
   * A list of InstrumentationLibraryLogs that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
   * scope_logs SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
   * and scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_logs field MAY also set
   * scope_logs to carry the same logs, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_logs and
   * SHOULD NOT set instrumentation_library_logs.
   * JSON receivers SHOULD check if instrumentation_library_logs is set and
   * scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<? extends com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder> 
      getInstrumentationLibraryLogsOrBuilderList() {
    return instrumentationLibraryLogs_;
  }
  /**
   * <pre>
   * A list of InstrumentationLibraryLogs that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
   * scope_logs SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
   * and scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_logs field MAY also set
   * scope_logs to carry the same logs, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_logs and
   * SHOULD NOT set instrumentation_library_logs.
   * JSON receivers SHOULD check if instrumentation_library_logs is set and
   * scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public int getInstrumentationLibraryLogsCount() {
    return instrumentationLibraryLogs_.size();
  }
  /**
   * <pre>
   * A list of InstrumentationLibraryLogs that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
   * scope_logs SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
   * and scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_logs field MAY also set
   * scope_logs to carry the same logs, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_logs and
   * SHOULD NOT set instrumentation_library_logs.
   * JSON receivers SHOULD check if instrumentation_library_logs is set and
   * scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs getInstrumentationLibraryLogs(int index) {
    return instrumentationLibraryLogs_.get(index);
  }
  /**
   * <pre>
   * A list of InstrumentationLibraryLogs that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
   * scope_logs SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
   * and scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_logs field MAY also set
   * scope_logs to carry the same logs, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_logs and
   * SHOULD NOT set instrumentation_library_logs.
   * JSON receivers SHOULD check if instrumentation_library_logs is set and
   * scope_logs is not set then the value in instrumentation_library_logs
   * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
   * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder getInstrumentationLibraryLogsOrBuilder(
      int index) {
    return instrumentationLibraryLogs_.get(index);
  }

  public static final int SCHEMA_URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object schemaUrl_;
  /**
   * <pre>
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_logs" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
   * @return The schemaUrl.
   */
  @java.lang.Override
  public java.lang.String getSchemaUrl() {
    java.lang.Object ref = schemaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_logs" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
   * @return The bytes for schemaUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaUrlBytes() {
    java.lang.Object ref = schemaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    for (int i = 0; i < scopeLogs_.size(); i++) {
      output.writeMessage(2, scopeLogs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, schemaUrl_);
    }
    for (int i = 0; i < instrumentationLibraryLogs_.size(); i++) {
      output.writeMessage(1000, instrumentationLibraryLogs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    for (int i = 0; i < scopeLogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, scopeLogs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, schemaUrl_);
    }
    for (int i = 0; i < instrumentationLibraryLogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1000, instrumentationLibraryLogs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.opentelemetry.proto.logs.v1.ResourceLogs)) {
      return super.equals(obj);
    }
    com.opentelemetry.proto.logs.v1.ResourceLogs other = (com.opentelemetry.proto.logs.v1.ResourceLogs) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getScopeLogsList()
        .equals(other.getScopeLogsList())) return false;
    if (!getInstrumentationLibraryLogsList()
        .equals(other.getInstrumentationLibraryLogsList())) return false;
    if (!getSchemaUrl()
        .equals(other.getSchemaUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    if (getScopeLogsCount() > 0) {
      hash = (37 * hash) + SCOPE_LOGS_FIELD_NUMBER;
      hash = (53 * hash) + getScopeLogsList().hashCode();
    }
    if (getInstrumentationLibraryLogsCount() > 0) {
      hash = (37 * hash) + INSTRUMENTATION_LIBRARY_LOGS_FIELD_NUMBER;
      hash = (53 * hash) + getInstrumentationLibraryLogsList().hashCode();
    }
    hash = (37 * hash) + SCHEMA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.opentelemetry.proto.logs.v1.ResourceLogs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.opentelemetry.proto.logs.v1.ResourceLogs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A collection of ScopeLogs from a Resource.
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.logs.v1.ResourceLogs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.logs.v1.ResourceLogs)
      com.opentelemetry.proto.logs.v1.ResourceLogsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opentelemetry.proto.logs.v1.LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opentelemetry.proto.logs.v1.LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.opentelemetry.proto.logs.v1.ResourceLogs.class, com.opentelemetry.proto.logs.v1.ResourceLogs.Builder.class);
    }

    // Construct using com.opentelemetry.proto.logs.v1.ResourceLogs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getScopeLogsFieldBuilder();
        getInstrumentationLibraryLogsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      if (scopeLogsBuilder_ == null) {
        scopeLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        scopeLogsBuilder_.clear();
      }
      if (instrumentationLibraryLogsBuilder_ == null) {
        instrumentationLibraryLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        instrumentationLibraryLogsBuilder_.clear();
      }
      schemaUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.opentelemetry.proto.logs.v1.LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
    }

    @java.lang.Override
    public com.opentelemetry.proto.logs.v1.ResourceLogs getDefaultInstanceForType() {
      return com.opentelemetry.proto.logs.v1.ResourceLogs.getDefaultInstance();
    }

    @java.lang.Override
    public com.opentelemetry.proto.logs.v1.ResourceLogs build() {
      com.opentelemetry.proto.logs.v1.ResourceLogs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.opentelemetry.proto.logs.v1.ResourceLogs buildPartial() {
      com.opentelemetry.proto.logs.v1.ResourceLogs result = new com.opentelemetry.proto.logs.v1.ResourceLogs(this);
      int from_bitField0_ = bitField0_;
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      if (scopeLogsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          scopeLogs_ = java.util.Collections.unmodifiableList(scopeLogs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scopeLogs_ = scopeLogs_;
      } else {
        result.scopeLogs_ = scopeLogsBuilder_.build();
      }
      if (instrumentationLibraryLogsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          instrumentationLibraryLogs_ = java.util.Collections.unmodifiableList(instrumentationLibraryLogs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.instrumentationLibraryLogs_ = instrumentationLibraryLogs_;
      } else {
        result.instrumentationLibraryLogs_ = instrumentationLibraryLogsBuilder_.build();
      }
      result.schemaUrl_ = schemaUrl_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.opentelemetry.proto.logs.v1.ResourceLogs) {
        return mergeFrom((com.opentelemetry.proto.logs.v1.ResourceLogs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.opentelemetry.proto.logs.v1.ResourceLogs other) {
      if (other == com.opentelemetry.proto.logs.v1.ResourceLogs.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (scopeLogsBuilder_ == null) {
        if (!other.scopeLogs_.isEmpty()) {
          if (scopeLogs_.isEmpty()) {
            scopeLogs_ = other.scopeLogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScopeLogsIsMutable();
            scopeLogs_.addAll(other.scopeLogs_);
          }
          onChanged();
        }
      } else {
        if (!other.scopeLogs_.isEmpty()) {
          if (scopeLogsBuilder_.isEmpty()) {
            scopeLogsBuilder_.dispose();
            scopeLogsBuilder_ = null;
            scopeLogs_ = other.scopeLogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            scopeLogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getScopeLogsFieldBuilder() : null;
          } else {
            scopeLogsBuilder_.addAllMessages(other.scopeLogs_);
          }
        }
      }
      if (instrumentationLibraryLogsBuilder_ == null) {
        if (!other.instrumentationLibraryLogs_.isEmpty()) {
          if (instrumentationLibraryLogs_.isEmpty()) {
            instrumentationLibraryLogs_ = other.instrumentationLibraryLogs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInstrumentationLibraryLogsIsMutable();
            instrumentationLibraryLogs_.addAll(other.instrumentationLibraryLogs_);
          }
          onChanged();
        }
      } else {
        if (!other.instrumentationLibraryLogs_.isEmpty()) {
          if (instrumentationLibraryLogsBuilder_.isEmpty()) {
            instrumentationLibraryLogsBuilder_.dispose();
            instrumentationLibraryLogsBuilder_ = null;
            instrumentationLibraryLogs_ = other.instrumentationLibraryLogs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            instrumentationLibraryLogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInstrumentationLibraryLogsFieldBuilder() : null;
          } else {
            instrumentationLibraryLogsBuilder_.addAllMessages(other.instrumentationLibraryLogs_);
          }
        }
      }
      if (!other.getSchemaUrl().isEmpty()) {
        schemaUrl_ = other.schemaUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.opentelemetry.proto.logs.v1.ResourceLogs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.opentelemetry.proto.logs.v1.ResourceLogs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.opentelemetry.proto.resource.v1.Resource resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.opentelemetry.proto.resource.v1.Resource, com.opentelemetry.proto.resource.v1.Resource.Builder, com.opentelemetry.proto.resource.v1.ResourceOrBuilder> resourceBuilder_;
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     * @return The resource.
     */
    public com.opentelemetry.proto.resource.v1.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? com.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    public Builder setResource(com.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    public Builder setResource(
        com.opentelemetry.proto.resource.v1.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    public Builder mergeResource(com.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            com.opentelemetry.proto.resource.v1.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    public com.opentelemetry.proto.resource.v1.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    public com.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            com.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.opentelemetry.proto.resource.v1.Resource, com.opentelemetry.proto.resource.v1.Resource.Builder, com.opentelemetry.proto.resource.v1.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.opentelemetry.proto.resource.v1.Resource, com.opentelemetry.proto.resource.v1.Resource.Builder, com.opentelemetry.proto.resource.v1.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.util.List<com.opentelemetry.proto.logs.v1.ScopeLogs> scopeLogs_ =
      java.util.Collections.emptyList();
    private void ensureScopeLogsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        scopeLogs_ = new java.util.ArrayList<com.opentelemetry.proto.logs.v1.ScopeLogs>(scopeLogs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.opentelemetry.proto.logs.v1.ScopeLogs, com.opentelemetry.proto.logs.v1.ScopeLogs.Builder, com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder> scopeLogsBuilder_;

    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public java.util.List<com.opentelemetry.proto.logs.v1.ScopeLogs> getScopeLogsList() {
      if (scopeLogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scopeLogs_);
      } else {
        return scopeLogsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public int getScopeLogsCount() {
      if (scopeLogsBuilder_ == null) {
        return scopeLogs_.size();
      } else {
        return scopeLogsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public com.opentelemetry.proto.logs.v1.ScopeLogs getScopeLogs(int index) {
      if (scopeLogsBuilder_ == null) {
        return scopeLogs_.get(index);
      } else {
        return scopeLogsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder setScopeLogs(
        int index, com.opentelemetry.proto.logs.v1.ScopeLogs value) {
      if (scopeLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeLogsIsMutable();
        scopeLogs_.set(index, value);
        onChanged();
      } else {
        scopeLogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder setScopeLogs(
        int index, com.opentelemetry.proto.logs.v1.ScopeLogs.Builder builderForValue) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        scopeLogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder addScopeLogs(com.opentelemetry.proto.logs.v1.ScopeLogs value) {
      if (scopeLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeLogsIsMutable();
        scopeLogs_.add(value);
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder addScopeLogs(
        int index, com.opentelemetry.proto.logs.v1.ScopeLogs value) {
      if (scopeLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeLogsIsMutable();
        scopeLogs_.add(index, value);
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder addScopeLogs(
        com.opentelemetry.proto.logs.v1.ScopeLogs.Builder builderForValue) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.add(builderForValue.build());
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder addScopeLogs(
        int index, com.opentelemetry.proto.logs.v1.ScopeLogs.Builder builderForValue) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder addAllScopeLogs(
        java.lang.Iterable<? extends com.opentelemetry.proto.logs.v1.ScopeLogs> values) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scopeLogs_);
        onChanged();
      } else {
        scopeLogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder clearScopeLogs() {
      if (scopeLogsBuilder_ == null) {
        scopeLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        scopeLogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public Builder removeScopeLogs(int index) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.remove(index);
        onChanged();
      } else {
        scopeLogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public com.opentelemetry.proto.logs.v1.ScopeLogs.Builder getScopeLogsBuilder(
        int index) {
      return getScopeLogsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder getScopeLogsOrBuilder(
        int index) {
      if (scopeLogsBuilder_ == null) {
        return scopeLogs_.get(index);  } else {
        return scopeLogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public java.util.List<? extends com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder> 
         getScopeLogsOrBuilderList() {
      if (scopeLogsBuilder_ != null) {
        return scopeLogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scopeLogs_);
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public com.opentelemetry.proto.logs.v1.ScopeLogs.Builder addScopeLogsBuilder() {
      return getScopeLogsFieldBuilder().addBuilder(
          com.opentelemetry.proto.logs.v1.ScopeLogs.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public com.opentelemetry.proto.logs.v1.ScopeLogs.Builder addScopeLogsBuilder(
        int index) {
      return getScopeLogsFieldBuilder().addBuilder(
          index, com.opentelemetry.proto.logs.v1.ScopeLogs.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2 [json_name = "scopeLogs"];</code>
     */
    public java.util.List<com.opentelemetry.proto.logs.v1.ScopeLogs.Builder> 
         getScopeLogsBuilderList() {
      return getScopeLogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.opentelemetry.proto.logs.v1.ScopeLogs, com.opentelemetry.proto.logs.v1.ScopeLogs.Builder, com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder> 
        getScopeLogsFieldBuilder() {
      if (scopeLogsBuilder_ == null) {
        scopeLogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.opentelemetry.proto.logs.v1.ScopeLogs, com.opentelemetry.proto.logs.v1.ScopeLogs.Builder, com.opentelemetry.proto.logs.v1.ScopeLogsOrBuilder>(
                scopeLogs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        scopeLogs_ = null;
      }
      return scopeLogsBuilder_;
    }

    private java.util.List<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs> instrumentationLibraryLogs_ =
      java.util.Collections.emptyList();
    private void ensureInstrumentationLibraryLogsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        instrumentationLibraryLogs_ = new java.util.ArrayList<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs>(instrumentationLibraryLogs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder> instrumentationLibraryLogsBuilder_;

    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs> getInstrumentationLibraryLogsList() {
      if (instrumentationLibraryLogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instrumentationLibraryLogs_);
      } else {
        return instrumentationLibraryLogsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public int getInstrumentationLibraryLogsCount() {
      if (instrumentationLibraryLogsBuilder_ == null) {
        return instrumentationLibraryLogs_.size();
      } else {
        return instrumentationLibraryLogsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs getInstrumentationLibraryLogs(int index) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        return instrumentationLibraryLogs_.get(index);
      } else {
        return instrumentationLibraryLogsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setInstrumentationLibraryLogs(
        int index, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs value) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.set(index, value);
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setInstrumentationLibraryLogs(
        int index, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder builderForValue) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addInstrumentationLibraryLogs(com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs value) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.add(value);
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addInstrumentationLibraryLogs(
        int index, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs value) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.add(index, value);
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addInstrumentationLibraryLogs(
        com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder builderForValue) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.add(builderForValue.build());
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addInstrumentationLibraryLogs(
        int index, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder builderForValue) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAllInstrumentationLibraryLogs(
        java.lang.Iterable<? extends com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs> values) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        ensureInstrumentationLibraryLogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instrumentationLibraryLogs_);
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearInstrumentationLibraryLogs() {
      if (instrumentationLibraryLogsBuilder_ == null) {
        instrumentationLibraryLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder removeInstrumentationLibraryLogs(int index) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        ensureInstrumentationLibraryLogsIsMutable();
        instrumentationLibraryLogs_.remove(index);
        onChanged();
      } else {
        instrumentationLibraryLogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder getInstrumentationLibraryLogsBuilder(
        int index) {
      return getInstrumentationLibraryLogsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder getInstrumentationLibraryLogsOrBuilder(
        int index) {
      if (instrumentationLibraryLogsBuilder_ == null) {
        return instrumentationLibraryLogs_.get(index);  } else {
        return instrumentationLibraryLogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<? extends com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder> 
         getInstrumentationLibraryLogsOrBuilderList() {
      if (instrumentationLibraryLogsBuilder_ != null) {
        return instrumentationLibraryLogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instrumentationLibraryLogs_);
      }
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder addInstrumentationLibraryLogsBuilder() {
      return getInstrumentationLibraryLogsFieldBuilder().addBuilder(
          com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder addInstrumentationLibraryLogsBuilder(
        int index) {
      return getInstrumentationLibraryLogsFieldBuilder().addBuilder(
          index, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of InstrumentationLibraryLogs that originate from a resource.
     * This field is deprecated and will be removed after grace period expires on June 15, 2022.
     * During the grace period the following rules SHOULD be followed:
     * For Binary Protobufs
     * ====================
     * Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead
     * scope_logs SHOULD be set.
     * Binary Protobuf receivers SHOULD check if instrumentation_library_logs is set
     * and scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs SHOULD be ignored.
     * For JSON
     * ========
     * JSON senders that set instrumentation_library_logs field MAY also set
     * scope_logs to carry the same logs, essentially double-publishing the same data.
     * Such double-publishing MAY be controlled by a user-settable option.
     * If double-publishing is not used then the senders SHOULD set scope_logs and
     * SHOULD NOT set instrumentation_library_logs.
     * JSON receivers SHOULD check if instrumentation_library_logs is set and
     * scope_logs is not set then the value in instrumentation_library_logs
     * SHOULD be used instead by converting InstrumentationLibraryLogs into ScopeLogs.
     * If scope_logs is set then instrumentation_library_logs field SHOULD be ignored.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 1000 [json_name = "instrumentationLibraryLogs", deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder> 
         getInstrumentationLibraryLogsBuilderList() {
      return getInstrumentationLibraryLogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder> 
        getInstrumentationLibraryLogsFieldBuilder() {
      if (instrumentationLibraryLogsBuilder_ == null) {
        instrumentationLibraryLogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.Builder, com.opentelemetry.proto.logs.v1.InstrumentationLibraryLogsOrBuilder>(
                instrumentationLibraryLogs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        instrumentationLibraryLogs_ = null;
      }
      return instrumentationLibraryLogsBuilder_;
    }

    private java.lang.Object schemaUrl_ = "";
    /**
     * <pre>
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
     * @return The schemaUrl.
     */
    public java.lang.String getSchemaUrl() {
      java.lang.Object ref = schemaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
     * @return The bytes for schemaUrl.
     */
    public com.google.protobuf.ByteString
        getSchemaUrlBytes() {
      java.lang.Object ref = schemaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
     * @param value The schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaUrl() {
      
      schemaUrl_ = getDefaultInstance().getSchemaUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
     * @param value The bytes for schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.logs.v1.ResourceLogs)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.logs.v1.ResourceLogs)
  private static final com.opentelemetry.proto.logs.v1.ResourceLogs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.opentelemetry.proto.logs.v1.ResourceLogs();
  }

  public static com.opentelemetry.proto.logs.v1.ResourceLogs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceLogs>
      PARSER = new com.google.protobuf.AbstractParser<ResourceLogs>() {
    @java.lang.Override
    public ResourceLogs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceLogs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceLogs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceLogs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.opentelemetry.proto.logs.v1.ResourceLogs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

