// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/logs/v1/logs_service.proto

package com.opentelemetry.proto.collector.logs.v1;

public interface ExportLogsServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An array of ResourceLogs.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1 [json_name = "resourceLogs"];</code>
   */
  java.util.List<com.opentelemetry.proto.logs.v1.ResourceLogs> 
      getResourceLogsList();
  /**
   * <pre>
   * An array of ResourceLogs.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1 [json_name = "resourceLogs"];</code>
   */
  com.opentelemetry.proto.logs.v1.ResourceLogs getResourceLogs(int index);
  /**
   * <pre>
   * An array of ResourceLogs.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1 [json_name = "resourceLogs"];</code>
   */
  int getResourceLogsCount();
  /**
   * <pre>
   * An array of ResourceLogs.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1 [json_name = "resourceLogs"];</code>
   */
  java.util.List<? extends com.opentelemetry.proto.logs.v1.ResourceLogsOrBuilder> 
      getResourceLogsOrBuilderList();
  /**
   * <pre>
   * An array of ResourceLogs.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1 [json_name = "resourceLogs"];</code>
   */
  com.opentelemetry.proto.logs.v1.ResourceLogsOrBuilder getResourceLogsOrBuilder(
      int index);
}
