// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/logs/v1/logs_service.proto

package com.opentelemetry.proto.collector.logs.v1;

public final class LogsServiceProto {
  private LogsServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8opentelemetry/proto/collector/logs/v1/" +
      "logs_service.proto\022%opentelemetry.proto." +
      "collector.logs.v1\032&opentelemetry/proto/l" +
      "ogs/v1/logs.proto\"j\n\030ExportLogsServiceRe" +
      "quest\022N\n\rresource_logs\030\001 \003(\0132).opentelem" +
      "etry.proto.logs.v1.ResourceLogsR\014resourc" +
      "eLogs\"\033\n\031ExportLogsServiceResponse2\235\001\n\013L" +
      "ogsService\022\215\001\n\006Export\022?.opentelemetry.pr" +
      "oto.collector.logs.v1.ExportLogsServiceR" +
      "equest\032@.opentelemetry.proto.collector.l" +
      "ogs.v1.ExportLogsServiceResponse\"\000B\250\002\n)c" +
      "om.opentelemetry.proto.collector.logs.v1" +
      "B\020LogsServiceProtoP\001Z0go.opentelemetry.i" +
      "o/proto/otlp/collector/logs/v1\242\002\004OPCL\252\002%" +
      "Opentelemetry.Proto.Collector.Logs.V1\312\002%" +
      "Opentelemetry\\Proto\\Collector\\Logs\\V1\342\0021" +
      "Opentelemetry\\Proto\\Collector\\Logs\\V1\\GP" +
      "BMetadata\352\002)Opentelemetry::Proto::Collec" +
      "tor::Logs::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.opentelemetry.proto.logs.v1.LogsProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_descriptor,
        new java.lang.String[] { "ResourceLogs", });
    internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_descriptor,
        new java.lang.String[] { });
    com.opentelemetry.proto.logs.v1.LogsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
