// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/trace/v1/trace_service.proto

package com.opentelemetry.proto.collector.trace.v1;

public interface ExportTraceServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse)
    com.google.protobuf.MessageOrBuilder {
}
