// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/metrics/v1/metrics_service.proto

package com.opentelemetry.proto.collector.metrics.v1;

public final class MetricsServiceProto {
  private MetricsServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>opentelemetry/proto/collector/metrics/" +
      "v1/metrics_service.proto\022(opentelemetry." +
      "proto.collector.metrics.v1\032,opentelemetr" +
      "y/proto/metrics/v1/metrics.proto\"y\n\033Expo" +
      "rtMetricsServiceRequest\022Z\n\020resource_metr" +
      "ics\030\001 \003(\0132/.opentelemetry.proto.metrics." +
      "v1.ResourceMetricsR\017resourceMetrics\"\036\n\034E" +
      "xportMetricsServiceResponse2\254\001\n\016MetricsS" +
      "ervice\022\231\001\n\006Export\022E.opentelemetry.proto." +
      "collector.metrics.v1.ExportMetricsServic" +
      "eRequest\032F.opentelemetry.proto.collector" +
      ".metrics.v1.ExportMetricsServiceResponse" +
      "\"\000B\275\002\n,com.opentelemetry.proto.collector" +
      ".metrics.v1B\023MetricsServiceProtoP\001Z3go.o" +
      "pentelemetry.io/proto/otlp/collector/met" +
      "rics/v1\242\002\004OPCM\252\002(Opentelemetry.Proto.Col" +
      "lector.Metrics.V1\312\002(Opentelemetry\\Proto\\" +
      "Collector\\Metrics\\V1\342\0024Opentelemetry\\Pro" +
      "to\\Collector\\Metrics\\V1\\GPBMetadata\352\002,Op" +
      "entelemetry::Proto::Collector::Metrics::" +
      "V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.opentelemetry.proto.metrics.v1.MetricsProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceRequest_descriptor,
        new java.lang.String[] { "ResourceMetrics", });
    internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsServiceResponse_descriptor,
        new java.lang.String[] { });
    com.opentelemetry.proto.metrics.v1.MetricsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
