// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/resource/v1/resource.proto

package com.opentelemetry.proto.resource.v1;

public final class ResourceProto {
  private ResourceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_resource_v1_Resource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_resource_v1_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.opentelemetry/proto/resource/v1/resour" +
      "ce.proto\022\037opentelemetry.proto.resource.v" +
      "1\032*opentelemetry/proto/common/v1/common." +
      "proto\"\215\001\n\010Resource\022G\n\nattributes\030\001 \003(\0132\'" +
      ".opentelemetry.proto.common.v1.KeyValueR" +
      "\nattributes\0228\n\030dropped_attributes_count\030" +
      "\002 \001(\rR\026droppedAttributesCountB\377\001\n#com.op" +
      "entelemetry.proto.resource.v1B\rResourceP" +
      "rotoP\001Z*go.opentelemetry.io/proto/otlp/r" +
      "esource/v1\242\002\003OPR\252\002\037Opentelemetry.Proto.R" +
      "esource.V1\312\002\037Opentelemetry\\Proto\\Resourc" +
      "e\\V1\342\002+Opentelemetry\\Proto\\Resource\\V1\\G" +
      "PBMetadata\352\002\"Opentelemetry::Proto::Resou" +
      "rce::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_resource_v1_Resource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_resource_v1_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_resource_v1_Resource_descriptor,
        new java.lang.String[] { "Attributes", "DroppedAttributesCount", });
    com.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
