// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/trace/v1/trace.proto

package com.opentelemetry.proto.trace.v1;

public interface ScopeSpansOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.trace.v1.ScopeSpans)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The instrumentation scope information for the spans in this message.
   * Semantically when InstrumentationScope isn't set, it is equivalent with
   * an empty instrumentation scope name (unknown).
   * </pre>
   *
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 1 [json_name = "scope"];</code>
   * @return Whether the scope field is set.
   */
  boolean hasScope();
  /**
   * <pre>
   * The instrumentation scope information for the spans in this message.
   * Semantically when InstrumentationScope isn't set, it is equivalent with
   * an empty instrumentation scope name (unknown).
   * </pre>
   *
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 1 [json_name = "scope"];</code>
   * @return The scope.
   */
  com.opentelemetry.proto.common.v1.InstrumentationScope getScope();
  /**
   * <pre>
   * The instrumentation scope information for the spans in this message.
   * Semantically when InstrumentationScope isn't set, it is equivalent with
   * an empty instrumentation scope name (unknown).
   * </pre>
   *
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 1 [json_name = "scope"];</code>
   */
  com.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder getScopeOrBuilder();

  /**
   * <pre>
   * A list of Spans that originate from an instrumentation scope.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.Span spans = 2 [json_name = "spans"];</code>
   */
  java.util.List<com.opentelemetry.proto.trace.v1.Span> 
      getSpansList();
  /**
   * <pre>
   * A list of Spans that originate from an instrumentation scope.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.Span spans = 2 [json_name = "spans"];</code>
   */
  com.opentelemetry.proto.trace.v1.Span getSpans(int index);
  /**
   * <pre>
   * A list of Spans that originate from an instrumentation scope.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.Span spans = 2 [json_name = "spans"];</code>
   */
  int getSpansCount();
  /**
   * <pre>
   * A list of Spans that originate from an instrumentation scope.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.Span spans = 2 [json_name = "spans"];</code>
   */
  java.util.List<? extends com.opentelemetry.proto.trace.v1.SpanOrBuilder> 
      getSpansOrBuilderList();
  /**
   * <pre>
   * A list of Spans that originate from an instrumentation scope.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.Span spans = 2 [json_name = "spans"];</code>
   */
  com.opentelemetry.proto.trace.v1.SpanOrBuilder getSpansOrBuilder(
      int index);

  /**
   * <pre>
   * This schema_url applies to all spans and span events in the "spans" field.
   * </pre>
   *
   * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
   * @return The schemaUrl.
   */
  java.lang.String getSchemaUrl();
  /**
   * <pre>
   * This schema_url applies to all spans and span events in the "spans" field.
   * </pre>
   *
   * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
   * @return The bytes for schemaUrl.
   */
  com.google.protobuf.ByteString
      getSchemaUrlBytes();
}
