// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/metrics/v1/metrics.proto

package com.opentelemetry.proto.metrics.v1;

public final class MetricsProto {
  private MetricsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,opentelemetry/proto/metrics/v1/metrics" +
      ".proto\022\036opentelemetry.proto.metrics.v1\032*" +
      "opentelemetry/proto/common/v1/common.pro" +
      "to\032.opentelemetry/proto/resource/v1/reso" +
      "urce.proto\"i\n\013MetricsData\022Z\n\020resource_me" +
      "trics\030\001 \003(\0132/.opentelemetry.proto.metric" +
      "s.v1.ResourceMetricsR\017resourceMetrics\"\327\002" +
      "\n\017ResourceMetrics\022E\n\010resource\030\001 \001(\0132).op" +
      "entelemetry.proto.resource.v1.ResourceR\010" +
      "resource\022Q\n\rscope_metrics\030\002 \003(\0132,.opente" +
      "lemetry.proto.metrics.v1.ScopeMetricsR\014s" +
      "copeMetrics\022\212\001\n\037instrumentation_library_" +
      "metrics\030\350\007 \003(\0132=.opentelemetry.proto.met" +
      "rics.v1.InstrumentationLibraryMetricsB\002\030" +
      "\001R\035instrumentationLibraryMetrics\022\035\n\nsche" +
      "ma_url\030\003 \001(\tR\tschemaUrl\"\272\001\n\014ScopeMetrics" +
      "\022I\n\005scope\030\001 \001(\01323.opentelemetry.proto.co" +
      "mmon.v1.InstrumentationScopeR\005scope\022@\n\007m" +
      "etrics\030\002 \003(\0132&.opentelemetry.proto.metri" +
      "cs.v1.MetricR\007metrics\022\035\n\nschema_url\030\003 \001(" +
      "\tR\tschemaUrl\"\364\001\n\035InstrumentationLibraryM" +
      "etrics\022n\n\027instrumentation_library\030\001 \001(\0132" +
      "5.opentelemetry.proto.common.v1.Instrume" +
      "ntationLibraryR\026instrumentationLibrary\022@" +
      "\n\007metrics\030\002 \003(\0132&.opentelemetry.proto.me" +
      "trics.v1.MetricR\007metrics\022\035\n\nschema_url\030\003" +
      " \001(\tR\tschemaUrl:\002\030\001\"\341\003\n\006Metric\022\022\n\004name\030\001" +
      " \001(\tR\004name\022 \n\013description\030\002 \001(\tR\013descrip" +
      "tion\022\022\n\004unit\030\003 \001(\tR\004unit\022=\n\005gauge\030\005 \001(\0132" +
      "%.opentelemetry.proto.metrics.v1.GaugeH\000" +
      "R\005gauge\0227\n\003sum\030\007 \001(\0132#.opentelemetry.pro" +
      "to.metrics.v1.SumH\000R\003sum\022I\n\thistogram\030\t " +
      "\001(\0132).opentelemetry.proto.metrics.v1.His" +
      "togramH\000R\thistogram\022k\n\025exponential_histo" +
      "gram\030\n \001(\01324.opentelemetry.proto.metrics" +
      ".v1.ExponentialHistogramH\000R\024exponentialH" +
      "istogram\022C\n\007summary\030\013 \001(\0132\'.opentelemetr" +
      "y.proto.metrics.v1.SummaryH\000R\007summaryB\006\n" +
      "\004dataJ\004\010\004\020\005J\004\010\006\020\007J\004\010\010\020\t\"Y\n\005Gauge\022P\n\013data" +
      "_points\030\001 \003(\0132/.opentelemetry.proto.metr" +
      "ics.v1.NumberDataPointR\ndataPoints\"\353\001\n\003S" +
      "um\022P\n\013data_points\030\001 \003(\0132/.opentelemetry." +
      "proto.metrics.v1.NumberDataPointR\ndataPo" +
      "ints\022o\n\027aggregation_temporality\030\002 \001(\01626." +
      "opentelemetry.proto.metrics.v1.Aggregati" +
      "onTemporalityR\026aggregationTemporality\022!\n" +
      "\014is_monotonic\030\003 \001(\010R\013isMonotonic\"\321\001\n\tHis" +
      "togram\022S\n\013data_points\030\001 \003(\01322.openteleme" +
      "try.proto.metrics.v1.HistogramDataPointR" +
      "\ndataPoints\022o\n\027aggregation_temporality\030\002" +
      " \001(\01626.opentelemetry.proto.metrics.v1.Ag" +
      "gregationTemporalityR\026aggregationTempora" +
      "lity\"\347\001\n\024ExponentialHistogram\022^\n\013data_po" +
      "ints\030\001 \003(\0132=.opentelemetry.proto.metrics" +
      ".v1.ExponentialHistogramDataPointR\ndataP" +
      "oints\022o\n\027aggregation_temporality\030\002 \001(\01626" +
      ".opentelemetry.proto.metrics.v1.Aggregat" +
      "ionTemporalityR\026aggregationTemporality\"\\" +
      "\n\007Summary\022Q\n\013data_points\030\001 \003(\01320.opentel" +
      "emetry.proto.metrics.v1.SummaryDataPoint" +
      "R\ndataPoints\"\326\002\n\017NumberDataPoint\022G\n\nattr" +
      "ibutes\030\007 \003(\0132\'.opentelemetry.proto.commo" +
      "n.v1.KeyValueR\nattributes\022/\n\024start_time_" +
      "unix_nano\030\002 \001(\006R\021startTimeUnixNano\022$\n\016ti" +
      "me_unix_nano\030\003 \001(\006R\014timeUnixNano\022\035\n\tas_d" +
      "ouble\030\004 \001(\001H\000R\010asDouble\022\027\n\006as_int\030\006 \001(\020H" +
      "\000R\005asInt\022F\n\texemplars\030\005 \003(\0132(.openteleme" +
      "try.proto.metrics.v1.ExemplarR\texemplars" +
      "\022\024\n\005flags\030\010 \001(\rR\005flagsB\007\n\005valueJ\004\010\001\020\002\"\331\003" +
      "\n\022HistogramDataPoint\022G\n\nattributes\030\t \003(\013" +
      "2\'.opentelemetry.proto.common.v1.KeyValu" +
      "eR\nattributes\022/\n\024start_time_unix_nano\030\002 " +
      "\001(\006R\021startTimeUnixNano\022$\n\016time_unix_nano" +
      "\030\003 \001(\006R\014timeUnixNano\022\024\n\005count\030\004 \001(\006R\005cou" +
      "nt\022\025\n\003sum\030\005 \001(\001H\000R\003sum\210\001\001\022#\n\rbucket_coun" +
      "ts\030\006 \003(\006R\014bucketCounts\022\'\n\017explicit_bound" +
      "s\030\007 \003(\001R\016explicitBounds\022F\n\texemplars\030\010 \003" +
      "(\0132(.opentelemetry.proto.metrics.v1.Exem" +
      "plarR\texemplars\022\024\n\005flags\030\n \001(\rR\005flags\022\025\n" +
      "\003min\030\013 \001(\001H\001R\003min\210\001\001\022\025\n\003max\030\014 \001(\001H\002R\003max" +
      "\210\001\001B\006\n\004_sumB\006\n\004_minB\006\n\004_maxJ\004\010\001\020\002\"\306\005\n\035Ex" +
      "ponentialHistogramDataPoint\022G\n\nattribute" +
      "s\030\001 \003(\0132\'.opentelemetry.proto.common.v1." +
      "KeyValueR\nattributes\022/\n\024start_time_unix_" +
      "nano\030\002 \001(\006R\021startTimeUnixNano\022$\n\016time_un" +
      "ix_nano\030\003 \001(\006R\014timeUnixNano\022\024\n\005count\030\004 \001" +
      "(\006R\005count\022\020\n\003sum\030\005 \001(\001R\003sum\022\024\n\005scale\030\006 \001" +
      "(\021R\005scale\022\035\n\nzero_count\030\007 \001(\006R\tzeroCount" +
      "\022a\n\010positive\030\010 \001(\0132E.opentelemetry.proto" +
      ".metrics.v1.ExponentialHistogramDataPoin" +
      "t.BucketsR\010positive\022a\n\010negative\030\t \001(\0132E." +
      "opentelemetry.proto.metrics.v1.Exponenti" +
      "alHistogramDataPoint.BucketsR\010negative\022\024" +
      "\n\005flags\030\n \001(\rR\005flags\022F\n\texemplars\030\013 \003(\0132" +
      "(.opentelemetry.proto.metrics.v1.Exempla" +
      "rR\texemplars\022\025\n\003min\030\014 \001(\001H\000R\003min\210\001\001\022\025\n\003m" +
      "ax\030\r \001(\001H\001R\003max\210\001\001\032F\n\007Buckets\022\026\n\006offset\030" +
      "\001 \001(\021R\006offset\022#\n\rbucket_counts\030\002 \003(\004R\014bu" +
      "cketCountsB\006\n\004_minB\006\n\004_max\"\246\003\n\020SummaryDa" +
      "taPoint\022G\n\nattributes\030\007 \003(\0132\'.openteleme" +
      "try.proto.common.v1.KeyValueR\nattributes" +
      "\022/\n\024start_time_unix_nano\030\002 \001(\006R\021startTim" +
      "eUnixNano\022$\n\016time_unix_nano\030\003 \001(\006R\014timeU" +
      "nixNano\022\024\n\005count\030\004 \001(\006R\005count\022\020\n\003sum\030\005 \001" +
      "(\001R\003sum\022i\n\017quantile_values\030\006 \003(\0132@.opent" +
      "elemetry.proto.metrics.v1.SummaryDataPoi" +
      "nt.ValueAtQuantileR\016quantileValues\022\024\n\005fl" +
      "ags\030\010 \001(\rR\005flags\032C\n\017ValueAtQuantile\022\032\n\010q" +
      "uantile\030\001 \001(\001R\010quantile\022\024\n\005value\030\002 \001(\001R\005" +
      "valueJ\004\010\001\020\002\"\205\002\n\010Exemplar\022X\n\023filtered_att" +
      "ributes\030\007 \003(\0132\'.opentelemetry.proto.comm" +
      "on.v1.KeyValueR\022filteredAttributes\022$\n\016ti" +
      "me_unix_nano\030\002 \001(\006R\014timeUnixNano\022\035\n\tas_d" +
      "ouble\030\003 \001(\001H\000R\010asDouble\022\027\n\006as_int\030\006 \001(\020H" +
      "\000R\005asInt\022\027\n\007span_id\030\004 \001(\014R\006spanId\022\031\n\010tra" +
      "ce_id\030\005 \001(\014R\007traceIdB\007\n\005valueJ\004\010\001\020\002*\214\001\n\026" +
      "AggregationTemporality\022\'\n#AGGREGATION_TE" +
      "MPORALITY_UNSPECIFIED\020\000\022!\n\035AGGREGATION_T" +
      "EMPORALITY_DELTA\020\001\022&\n\"AGGREGATION_TEMPOR" +
      "ALITY_CUMULATIVE\020\002*;\n\016DataPointFlags\022\r\n\t" +
      "FLAG_NONE\020\000\022\032\n\026FLAG_NO_RECORDED_VALUE\020\001B" +
      "\370\001\n\"com.opentelemetry.proto.metrics.v1B\014" +
      "MetricsProtoP\001Z)go.opentelemetry.io/prot" +
      "o/otlp/metrics/v1\242\002\003OPM\252\002\036Opentelemetry." +
      "Proto.Metrics.V1\312\002\036Opentelemetry\\Proto\\M" +
      "etrics\\V1\342\002*Opentelemetry\\Proto\\Metrics\\" +
      "V1\\GPBMetadata\352\002!Opentelemetry::Proto::M" +
      "etrics::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          com.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor,
        new java.lang.String[] { "ResourceMetrics", });
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor,
        new java.lang.String[] { "Resource", "ScopeMetrics", "InstrumentationLibraryMetrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_descriptor,
        new java.lang.String[] { "Scope", "Metrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_InstrumentationLibraryMetrics_descriptor,
        new java.lang.String[] { "InstrumentationLibrary", "Metrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor,
        new java.lang.String[] { "Name", "Description", "Unit", "Gauge", "Sum", "Histogram", "ExponentialHistogram", "Summary", "Data", });
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", "IsMonotonic", });
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor,
        new java.lang.String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor,
        new java.lang.String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "AsDouble", "AsInt", "Exemplars", "Flags", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "BucketCounts", "ExplicitBounds", "Exemplars", "Flags", "Min", "Max", "Sum", "Min", "Max", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "Scale", "ZeroCount", "Positive", "Negative", "Flags", "Exemplars", "Min", "Max", "Min", "Max", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor,
        new java.lang.String[] { "Offset", "BucketCounts", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor,
        new java.lang.String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "QuantileValues", "Flags", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor,
        new java.lang.String[] { "Quantile", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor,
        new java.lang.String[] { "FilteredAttributes", "TimeUnixNano", "AsDouble", "AsInt", "SpanId", "TraceId", "Value", });
    com.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    com.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
