// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/metrics/v1/metrics.proto

package com.opentelemetry.proto.metrics.v1;

public interface ResourceMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.metrics.v1.ResourceMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource for the metrics in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <pre>
   * The resource for the metrics in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
   * @return The resource.
   */
  com.opentelemetry.proto.resource.v1.Resource getResource();
  /**
   * <pre>
   * The resource for the metrics in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1 [json_name = "resource"];</code>
   */
  com.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <pre>
   * A list of metrics that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2 [json_name = "scopeMetrics"];</code>
   */
  java.util.List<com.opentelemetry.proto.metrics.v1.ScopeMetrics> 
      getScopeMetricsList();
  /**
   * <pre>
   * A list of metrics that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2 [json_name = "scopeMetrics"];</code>
   */
  com.opentelemetry.proto.metrics.v1.ScopeMetrics getScopeMetrics(int index);
  /**
   * <pre>
   * A list of metrics that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2 [json_name = "scopeMetrics"];</code>
   */
  int getScopeMetricsCount();
  /**
   * <pre>
   * A list of metrics that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2 [json_name = "scopeMetrics"];</code>
   */
  java.util.List<? extends com.opentelemetry.proto.metrics.v1.ScopeMetricsOrBuilder> 
      getScopeMetricsOrBuilderList();
  /**
   * <pre>
   * A list of metrics that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.ScopeMetrics scope_metrics = 2 [json_name = "scopeMetrics"];</code>
   */
  com.opentelemetry.proto.metrics.v1.ScopeMetricsOrBuilder getScopeMetricsOrBuilder(
      int index);

  /**
   * <pre>
   * A list of InstrumentationLibraryMetrics that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_metrics. Instead
   * scope_metrics SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_metrics is set
   * and scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_metrics field MAY also set
   * scope_metrics to carry the same metrics, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_metrics and
   * SHOULD NOT set instrumentation_library_metrics.
   * JSON receivers SHOULD check if instrumentation_library_metrics is set and
   * scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics instrumentation_library_metrics = 1000 [json_name = "instrumentationLibraryMetrics", deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<com.opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics> 
      getInstrumentationLibraryMetricsList();
  /**
   * <pre>
   * A list of InstrumentationLibraryMetrics that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_metrics. Instead
   * scope_metrics SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_metrics is set
   * and scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_metrics field MAY also set
   * scope_metrics to carry the same metrics, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_metrics and
   * SHOULD NOT set instrumentation_library_metrics.
   * JSON receivers SHOULD check if instrumentation_library_metrics is set and
   * scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics instrumentation_library_metrics = 1000 [json_name = "instrumentationLibraryMetrics", deprecated = true];</code>
   */
  @java.lang.Deprecated com.opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics getInstrumentationLibraryMetrics(int index);
  /**
   * <pre>
   * A list of InstrumentationLibraryMetrics that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_metrics. Instead
   * scope_metrics SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_metrics is set
   * and scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_metrics field MAY also set
   * scope_metrics to carry the same metrics, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_metrics and
   * SHOULD NOT set instrumentation_library_metrics.
   * JSON receivers SHOULD check if instrumentation_library_metrics is set and
   * scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics instrumentation_library_metrics = 1000 [json_name = "instrumentationLibraryMetrics", deprecated = true];</code>
   */
  @java.lang.Deprecated int getInstrumentationLibraryMetricsCount();
  /**
   * <pre>
   * A list of InstrumentationLibraryMetrics that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_metrics. Instead
   * scope_metrics SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_metrics is set
   * and scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_metrics field MAY also set
   * scope_metrics to carry the same metrics, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_metrics and
   * SHOULD NOT set instrumentation_library_metrics.
   * JSON receivers SHOULD check if instrumentation_library_metrics is set and
   * scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics instrumentation_library_metrics = 1000 [json_name = "instrumentationLibraryMetrics", deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<? extends com.opentelemetry.proto.metrics.v1.InstrumentationLibraryMetricsOrBuilder> 
      getInstrumentationLibraryMetricsOrBuilderList();
  /**
   * <pre>
   * A list of InstrumentationLibraryMetrics that originate from a resource.
   * This field is deprecated and will be removed after grace period expires on June 15, 2022.
   * During the grace period the following rules SHOULD be followed:
   * For Binary Protobufs
   * ====================
   * Binary Protobuf senders SHOULD NOT set instrumentation_library_metrics. Instead
   * scope_metrics SHOULD be set.
   * Binary Protobuf receivers SHOULD check if instrumentation_library_metrics is set
   * and scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics SHOULD be ignored.
   * For JSON
   * ========
   * JSON senders that set instrumentation_library_metrics field MAY also set
   * scope_metrics to carry the same metrics, essentially double-publishing the same data.
   * Such double-publishing MAY be controlled by a user-settable option.
   * If double-publishing is not used then the senders SHOULD set scope_metrics and
   * SHOULD NOT set instrumentation_library_metrics.
   * JSON receivers SHOULD check if instrumentation_library_metrics is set and
   * scope_metrics is not set then the value in instrumentation_library_metrics
   * SHOULD be used instead by converting InstrumentationLibraryMetrics into ScopeMetrics.
   * If scope_metrics is set then instrumentation_library_metrics field SHOULD be ignored.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.InstrumentationLibraryMetrics instrumentation_library_metrics = 1000 [json_name = "instrumentationLibraryMetrics", deprecated = true];</code>
   */
  @java.lang.Deprecated com.opentelemetry.proto.metrics.v1.InstrumentationLibraryMetricsOrBuilder getInstrumentationLibraryMetricsOrBuilder(
      int index);

  /**
   * <pre>
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_metrics" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
   * @return The schemaUrl.
   */
  java.lang.String getSchemaUrl();
  /**
   * <pre>
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_metrics" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3 [json_name = "schemaUrl"];</code>
   * @return The bytes for schemaUrl.
   */
  com.google.protobuf.ByteString
      getSchemaUrlBytes();
}
