// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/metrics/v1/metrics.proto

package com.opentelemetry.proto.metrics.v1;

public interface SumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.metrics.v1.Sum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1 [json_name = "dataPoints"];</code>
   */
  java.util.List<com.opentelemetry.proto.metrics.v1.NumberDataPoint> 
      getDataPointsList();
  /**
   * <code>repeated .opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1 [json_name = "dataPoints"];</code>
   */
  com.opentelemetry.proto.metrics.v1.NumberDataPoint getDataPoints(int index);
  /**
   * <code>repeated .opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1 [json_name = "dataPoints"];</code>
   */
  int getDataPointsCount();
  /**
   * <code>repeated .opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1 [json_name = "dataPoints"];</code>
   */
  java.util.List<? extends com.opentelemetry.proto.metrics.v1.NumberDataPointOrBuilder> 
      getDataPointsOrBuilderList();
  /**
   * <code>repeated .opentelemetry.proto.metrics.v1.NumberDataPoint data_points = 1 [json_name = "dataPoints"];</code>
   */
  com.opentelemetry.proto.metrics.v1.NumberDataPointOrBuilder getDataPointsOrBuilder(
      int index);

  /**
   * <pre>
   * aggregation_temporality describes if the aggregator reports delta changes
   * since last report time, or cumulative changes since a fixed start time.
   * </pre>
   *
   * <code>.opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2 [json_name = "aggregationTemporality"];</code>
   * @return The enum numeric value on the wire for aggregationTemporality.
   */
  int getAggregationTemporalityValue();
  /**
   * <pre>
   * aggregation_temporality describes if the aggregator reports delta changes
   * since last report time, or cumulative changes since a fixed start time.
   * </pre>
   *
   * <code>.opentelemetry.proto.metrics.v1.AggregationTemporality aggregation_temporality = 2 [json_name = "aggregationTemporality"];</code>
   * @return The aggregationTemporality.
   */
  com.opentelemetry.proto.metrics.v1.AggregationTemporality getAggregationTemporality();

  /**
   * <pre>
   * If "true" means that the sum is monotonic.
   * </pre>
   *
   * <code>bool is_monotonic = 3 [json_name = "isMonotonic"];</code>
   * @return The isMonotonic.
   */
  boolean getIsMonotonic();
}
